name: GitHub Profile Views

on:
  schedule:
    - cron: "*/10 * * * *"  # Har 10 min me run hoga

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install puppeteer

      - name: Run Puppeteer Script
        run: node views.js
        
