name: Auto View Booster

on:
  push:
  schedule:
    - cron: '*/10 * * * *' # Har 10 minute me run karega

jobs:
  view_booster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Send Views
        run: |
          for i in {1..10000}; do
            curl -s "https://github.com/otterai" > /dev/null
          done
          
